# Generated by Django 5.2.8 on 2025-11-13 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='URL to product image', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIVE', 'Receive'), ('SHIP', 'Ship')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.location')),
            ],
            options={
                'ordering': ['item', 'location'],
                'unique_together': {('item', 'location')},
            },
        ),
        migrations.CreateModel(
            name='TransactionJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id_str', models.CharField(db_index=True, help_text='Item ID at time of transaction (denormalized)', max_length=100)),
                ('item_name_str', models.CharField(blank=True, help_text='Item name at time of transaction (denormalized)', max_length=200)),
                ('location_name_str', models.CharField(db_index=True, help_text='Location name at time of transaction (denormalized)', max_length=100)),
                ('transaction_type', models.CharField(choices=[('RECEIVE', 'Receive'), ('SHIP', 'Ship')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('quantity_before', models.IntegerField(help_text='Quantity at location before this transaction')),
                ('quantity_after', models.IntegerField(help_text='Quantity at location after this transaction')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this transaction')),
                ('reference_number', models.CharField(blank=True, help_text='External reference number (PO, invoice, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, help_text='Reference to item (may be null if item deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='inventory.item')),
                ('location', models.ForeignKey(blank=True, help_text='Reference to location (may be null if location deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='inventory.location')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='inventory.stocktransaction')),
            ],
            options={
                'verbose_name': 'Transaction Journal Entry',
                'verbose_name_plural': 'Transaction Journal Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='inventory_t_created_f83b98_idx'), models.Index(fields=['item_id_str', 'location_name_str'], name='inventory_t_item_id_4bde08_idx'), models.Index(fields=['transaction_type'], name='inventory_t_transac_77fad2_idx')],
            },
        ),
    ]
