# Generated by Django 5.2.8 on 2025-11-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionjournal',
            name='transaction_type',
            field=models.CharField(choices=[('RECEIVE', 'Receive'), ('SHIP', 'Ship'), ('TRANSFER', 'Transfer')], max_length=10),
        ),
    ]
