# Generated by Django 5.2.8 on 2026-03-17 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionjournal',
            name='used_item_id_str',
            field=models.CharField(blank=True, help_text="Used item compound ID at time of transaction, e.g. '10317~1'", max_length=120),
        ),
        migrations.AddField(
            model_name='transactionjournal',
            name='used_item_notes',
            field=models.TextField(blank=True, help_text='Snapshot of used item condition notes at time of transaction'),
        ),
        migrations.CreateModel(
            name='UsedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_items', to='inventory.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_items', to='inventory.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item', 'suffix'],
                'unique_together': {('user', 'item', 'suffix')},
            },
        ),
    ]
