# Generated by Django 5.2.8 on 2025-12-09 15:35

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_user_to_location'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Add user field to StockTransaction
        migrations.AddField(
            model_name='stocktransaction',
            name='user',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transactions',
                to='auth.user'
            ),
        ),

        # Add user field to Inventory
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='inventory',
                to='auth.user'
            ),
        ),

        # Add user field to TransactionJournal
        migrations.AddField(
            model_name='transactionjournal',
            name='user',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='journal_entries',
                to='auth.user'
            ),
        ),

        # Update unique_together for Inventory to include user
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('user', 'item', 'location')},
        ),
    ]
